window:
  padding:
    x: 1
    y: 1
  opacity: 0.85
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: DaddyTimeMono Nerd Font
    style: Medium
  size: 8

draw_bold_text_with_bright_colors: true
colors:
  primary:
    background: "#282a36"
    #background: "#1B2631"
    foreground: "#F5F5F5"
#  normal:
#   black:
#   red:
#   green:
#   yellow:
#   blue:
#   magenta:
#   cyan:
#   white:
cursor:
  style:
    shape: Underline
    blinking: Always
    blink-interval: 750
selection:
  save_to_clipboard: true

live_config_reload: true

key_bindings: 
  - {key: Return, mods: Control|Shift, action: SpawnNewInstance}
